### ISSUE TITLE
Support for Middleware Sequence?

### ISSUE THREAD

**Issue by gtamas** [sourcefuse/loopback4-ratelimiter#11]
**Is your feature request related to a problem? Please describe.**

How can I use this with the new Middleware sequence?
I can't register the action the old way anymore.

**Describe the solution you'd like**

I need some way to add this to sequence.ts

```
import {MiddlewareSequence} from '@loopback/rest';

export class MySequence extends MiddlewareSequence {}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by samarpan-b** [comment]
It does not support middleware type binding. For using as middleware you can directly use express middleware library. 
But it's a good feature request.

Would you care to contribute for it ? @gtamas
