### ISSUE TITLE
Interceptor support to avoid sequence changes

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-ratelimiter#45]
**Is your feature request related to a problem? Please describe.**
The action based sequences are being phased out by loopback4, so it would be great if this library provides a middleware or interceptor to handle the ratelimiting.

**Describe the solution you'd like**
A interceptor that is bound by the ratelimiter component.

**Additional context**
Another issue with sequence based approach is that using this component would require a custom sequence which is not always possible.

**Comment by yeshamavani** [comment]
@samarpanB  
Provided a middleware https://github.com/sourcefuse/loopback4-ratelimiter/pull/72 please review
