### ISSUE TITLE
How to disable rate limiting on LB4 explorer path

### ISSUE THREAD

**Issue by AymenLoukil** [sourcefuse/loopback4-ratelimiter#76]
**Describe the bug**

I added the ratelimiter and my /explorer/ doesn't work anymore. How can I disable the rate limiter for the explorer?

Thanks

**Comment by Surbhi-sharma1** [comment]
@AymenLoukil Can you share the exact error message?

**Comment by yeshamavani** [comment]
@AymenLoukil if  you are facing this error 
Either the 'unsafe-inline' keyword, a hash ('sha256-DLbdWNBhwD1fyzUBjaE5Up3Y/4UCDB1OYv/c61qHL/I='), or a nonce ('nonce-...') is required to enable inline execution.
tried passing an empty object
then adding the following to your .env file should help 
CSP_SCRIPT_SRC_HASH='sha256-DLbdWNBhwD1fyzUBjaE5Up3Y/4UCDB1OYv/c61qHL/I='

correct me if I am wrong @Surbhi-sharma1

**Comment by AymenLoukil** [comment]
Hello @Surbhi-sharma1 

When i go to the explorer URL /app/explorer i get 429 Too Many Requests error. So how to exclude the explorer from rate limiting since it doesn't have a dedicated controller...?
Thanks

**Comment by Surbhi-sharma1** [comment]
Hello @AymenLoukil 
There is  a PR under to  disable ratelimiting for all APIs except those that are enabled using the decorator.
